version: '2'

services:
  rabbitmq:
    image: docker.io/bitnami/rabbitmq:3.9
    ports:
      - '4379:4369'
      - '6551:5551'
      - '6552:5552'
      - '6672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_SECURE_PASSWORD=yes
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=localmq012345
    volumes:
      - 'rabbitmq_data:/bitnami/rabbitmq/mnesia'
volumes:
  rabbitmq_data:
    driver: local
